### ISSUE TITLE
Issue when used on a tablet

### ISSUE THREAD

**Issue by gjrowe** [joeldbirch/superfish#1]
I have been trying to get this to work when accessed on my iPad and it doesn't seem to work because there is no "hover" on the iPad. It is all touch.

The problem appears when trying to get to the sub-menus. The menu does open; however, the page also immediately tries to access the page in the "href" of the parent menu that was clicked on. On the reload it closes the menu.  Had the same issue in some browsers on my Mac if the menu was clicked on instead of just being hovered over. (Not a PC user so not sure about that)

FOUND A FIX:
In the parent menu don't include an "href" at all. Change &lt;a href="#"&gt; to &lt;a&gt;
Doing so ensures that no action to go anywhere is given to the browser so nothing happens except for the sub-menu loading (as desired)

**Comment by YuvrajKhavad** [comment]
My problem fixed when i updates latest superfish.js files from http://users.tpg.com.au/j_birch/plugins/superfish/download/

Thanks
