### ISSUE TITLE
Compatible to jquery 1.X? (e.g.1.11.1)

### ISSUE THREAD

**Issue by kozi** [joeldbirch/superfish#129]
Is the current superfish 1.7.5 release compatible to the current jquery release 1.11.1? Is it possible to change the jquery dependency in bower.json to **">=1.8"**

**Comment by kozi** [comment]
Add a new release with updated bower.json!

See comment: https://github.com/joeldbirch/superfish/pull/130

**Comment by joeldbirch** [comment]
This has been done. Thanks!
