### ISSUE TITLE
Responsive behavior like FlexNav or Dropdowns in small resolution

### ISSUE THREAD

**Issue by slolo2000** [joeldbirch/superfish#131]
Hello,

Do you think it would be possible to add the same behavior like FlexNav or Dropdowns in small resolution. The aim is to have a nice and more user friendly menu even in small resolution.

![big-menu](https://cloud.githubusercontent.com/assets/10075509/5300544/6a5a7f2e-7bd1-11e4-925e-a0879f0b8b85.jpg)
becomes this in small resolution
![small-menu](https://cloud.githubusercontent.com/assets/10075509/5300545/6a5eb12a-7bd1-11e4-892a-e2738995a24d.jpg)

See Dropdowns informations : 
https://github.com/tessalt/dropdowns
http://webdesign.tutsplus.com/tutorials/big-menus-small-screens-responsive-multi-level-navigation--webdesign-8452 (for demo)

See FlexNav informations : 
https://github.com/indyplanets/flexnav (for source code and demo)

Thanks in advance and have a nice day.

**Comment by rolandbln** [comment]
Hi,

Well, I die it this way :
http://rh-balingen.de/MyMenu/
http://rh-balingen.de/MyMenu/responive.zip

( -: roland :- )

**Comment by joeldbirch** [comment]
I tend to `.superfish('destroy')` at small screens and initialise a more suitable nav system.

**Comment by slolo2000** [comment]
Hi joeldbirch,

Thanks for your answer. In fact I have done a trick to transform superfish menu to hamburger menu.
With just a little of javascript and a bit of css the result is quite satisfying.

I really think it could be a nice addition for your superfish plugin. It could be an option to transform superfish menu to hamburger menu when screen resolution is less then 480px for example.
If you want I can send you my code if you need an example.

Thanks and have a nice day.
