### ISSUE TITLE
Click event on superfish mobile version

### ISSUE THREAD

**Issue by cesaret** [joeldbirch/superfish#132]
Hi!

I've a problem in the superfish mobile version of my web http://www.estudigrafema.com/bitech.

The "normal" version is ok, as I want, but in the mobile version I can't click in the text of the first subitems level that has not subsubmenu (ex: "manuales"). In next sublevels I can click everywhere but I would like only to click in the text that has not more sublevels.

Any clue? Thanks.

**Comment by kuka** [comment]
Met with the same incompatibility. Did you find a solution?

**Comment by cesaret** [comment]
Hi kuka!

No, not yet.
