### ISSUE TITLE
Stop sf-hover appearing on certain elements?

### ISSUE THREAD

**Issue by dingo-d** [joeldbirch/superfish#135]
Is it possible to make superfish not add sfHover on megamenu list items?

Currently when I hover on megamenu list items I get the class, and superfish fires off and triggers the opacity animation, which makes list items flicker. Is it possible to exclude the superfish to add sfHover on megamenu list items? My megamenu has .sf-mega class.

**Comment by joeldbirch** [comment]
Why not simply configure Superfish to not use an opacity animation? If what I think you mean by "list items flicker" is correct, then maybe just try a height animation, or no animation (maybe set the speed to 1).

**Comment by dingo-d** [comment]
I figured out the problem in the end. The flickering happened because my megamenu list items had `display: inline-block` instead of `block` property. A stupid overlook on my part. I put the height and opacity in the end :D Works fine now.
