### ISSUE TITLE
Have you considered adding code to insert ARIA attributes for accessibility?

### ISSUE THREAD

**Issue by Scratch2k** [joeldbirch/superfish#136]
By default, it's up the dev to add the aria role attributes to the menu, which is fine, but not many people do.

The code which used to build this menu: http://examples.simplyaccessible.com/css-menu/option-6.html could be integrated into superfish to auto insert role="menuitem" & menu, menubar, aria-haspopup, aria-hidden and tabindex to build a more accessible end product.

Code snippet:
```

	// Add ARIA role to menubar and menu items
	$(this).attr('role', 'menubar').find('li').attr('role', 'menuitem');
	
	var top_level_links = $(this).find('> li > a');
	
	// Set tabIndex to -1 so that top_level_links can't receive focus until menu is open
	$(top_level_links).next('ul')
		.attr({ 'aria-hidden': 'true', 'role': 'menu' })
		.find('a')
			.attr('tabIndex',-1);
	
	// Adding aria-haspopup for appropriate items
	$(top_level_links).each(function(){
		if($(this).next('ul').length > 0)
			$(this).parent('li').attr('aria-haspopup', 'true');
	});
	
	$(top_level_links).hover(function(){
		$(this).closest('ul')
			.attr('aria-hidden', 'false')
			.find('.'+settings.menuHoverClass)
				.attr('aria-hidden', 'true')
				.removeClass(settings.menuHoverClass)
				.find('a')
					.attr('tabIndex',-1);
		$(this).next('ul')
			.attr('aria-hidden', 'false')
			.addClass(settings.menuHoverClass)
			.find('a').attr('tabIndex',0);
	});
	$(top_level_links).focus(function(){
		$(this).closest('ul')
			.attr('aria-hidden', 'false')
			.find('.'+settings.menuHoverClass)
				.attr('aria-hidden', 'true')
				.removeClass(settings.menuHoverClass)
				.find('a')
					.attr('tabIndex',-1);
		$(this).next('ul')
			.attr('aria-hidden', 'false')
			.addClass(settings.menuHoverClass)
			.find('a').attr('tabIndex',0);
	});
```	
What do you think?

(as a side note, the make the plug in even more accessible, the up and down arrows should be usable to navigate up and down a pop up menu)

**Comment by farroutt3fan** [comment]
The arrow key (up, down, right, left) in particular would be a huge bonus. I'm trying to figure this out on my own now, so would vote for it to be the next #1 feature request.

**Comment by carasmo** [comment]
That would be awesome!

**Comment by tmos** [comment]
:+1: for usability and accessiblity. Could be a great plus for the plugin to become a reference :)

**Comment by joeldbirch** [comment]
I'd really like this to be created as a separate plugin which can be chained onto the initial .superfish() call. It's the perfect candidate for this, and would keep the Superfish code lean and manageable. Great idea though, I certainly have been hoping someone creates this.

**Comment by mattpaz** [comment]
Just out of curiosity, did anyone wind up creating a separate plugin for this -- and for #181?
