### ISSUE TITLE
Are there any good styles, theme for superfish?

### ISSUE THREAD

**Issue by MonsterMMORPG** [joeldbirch/superfish#141]
I am willing to pay for a good one

I like superfish it is the best however i need a good styles for it

my current sites uses it however as you will also notice even my menu bar theme sucks sucks  (when you hover you will see)

ty

my sites : http://www.pokemonpets.com

http://www.monstermmorpg.com

**Comment by Antes** [comment]
You need CSS work. Send me mail if you want antes@simplemachines.org - what is on your mind with colors (if possible). You can send me mail in Turkish if you want, I'm writing in english because of others need to understand what I'm saying :P
