### ISSUE TITLE
menu hide in mobile nav

### ISSUE THREAD

**Issue by sandippatelp** [joeldbirch/superfish#144]
Hi,
menu works fine in desktop but it will hide in mobile version.
http://viyawedding.com/VW2015/sultan-11-3.php

Can you please advice me 
thanks

**Comment by joeldbirch** [comment]
Hello. Please see the support options here http://users.tpg.com.au/j_birch/plugins/superfish/download/#support

These GitHub issues are only for demonstrable bugs with the plugin.
