### ISSUE TITLE
Google maps 

### ISSUE THREAD

**Issue by josebedoya** [joeldbirch/superfish#146]
The map does not show in megamenu.
![screen shot 2015-10-27 at 1 27 06 pm](https://cloud.githubusercontent.com/assets/9865690/10768324/806c80a8-7cae-11e5-8462-11debad99418.png)

**Comment by joeldbirch** [comment]
It's likely that the map container must be visible so Google Maps can inspect its dimensions, etc. You may need to find a way to initialise your map before Superfish hides it.
