### ISSUE TITLE
Windows Phone compatibility

### ISSUE THREAD

**Issue by tyrex1975** [joeldbirch/superfish#147]
Hi - I've noticed that Superfish doesn't work properly on Windows Phone devices (specifically WP8.1 with IE11). If you try out the Superfish nav-bar examples, you'll notice that when you tap a sub menu, it jumps back to the currently shown main menu. So you can't actually select anything.

A bit of digging this evening has shown me that the reason for this is an incorrect UserAgent string is being reported by the browser and forcing Superfish to think it is an iOS device.
http://www.neowin.net/news/ie11-fakes-user-agent-to-fool-gmail-in-windows-phone-81-gdr1-update

I'm no expert with GitHub, so I don't know how to submit a pull request, but we have resolved the problem by modifying line 22 in superfish.js:

From:
`
var ios = /iPhone|iPad|iPod/i.test(navigator.userAgent);
`

To:
`
var ios = /^(?!.*Windows Phone).*(iPhone|iPad|iPod)/i.test(navigator.userAgent);
`

There might be better ways of doing this, but I thought I would bring it to your attention.

PS. Thanks for a great plug-in.

**Comment by joeldbirch** [comment]
Hey, thank you so much for this report AND solution—it's wonderful to receive these sorts of "issues"!

I'll apply this fix ASAP. Really can't tell you how much I appreciate your work on this. Cheers!

**Comment by joeldbirch** [comment]
v1.7.7 should address this. FYI, I had to replace the dots in the regular expression in order to conform to the jshint rules I'm using. If you could test that it works that would be most appreciated. Thanks again!

**Comment by tyrex1975** [comment]
That's awesome, thank you for integrating into the main release.

I've updated our application with your new version and tested it successfully on the following platforms:

Desktop:
Chrome 47 (touch & mouse)
MS IE 7/8/9/10/11 (touch & mouse)
MS Edge (touch & mouse)
Firefox 40/41/42 (touch & mouse)
Safari 5.1.7 (touch & mouse)

Mobile:
WP8.1/IE11 (touch)
iPhone 4s IOS 9.1/9.2 (touch)
Chrome 46 Android 5.0.2 (touch)

If it's of interest, this is how we've implemented Superfish in our app, it has a little custom CSS to override superfish.css, but apart from that it's straight out of the box :)

![app](https://cloud.githubusercontent.com/assets/7656443/11714605/4ff8fbb6-9f33-11e5-9122-722936eb1da3.jpg)

**Comment by joeldbirch** [comment]
The pleasure was all mine! Really appreciate your help with this, and it's very cool to see how you're app has benefitted. Thanks again! 😀
