### ISSUE TITLE
Change from hover to click

### ISSUE THREAD

**Issue by connman** [joeldbirch/superfish#148]
As stated above, I would like to click on the parent menu and it pops out the submenu instead of just hovering over the parent menu. I'm not very familiar with javascript programming and I need help on altering the code in order to fulfill that requirement.

**Comment by Antes** [comment]
Can you try with; (if necessary remove `.sf-menu li.sfHover > ul` part)

```
.sf-menu li:focus > ul,
.sf-menu li.sfHover > ul {
	display: block;
}
```

https://github.com/joeldbirch/superfish/blob/master/src/css/superfish.css#L20-L23 (original)

**Comment by joeldbirch** [comment]
We split this functionality off into a separate plugin called Superclick. You can find it here https://github.com/joeldbirch/superclick
