### ISSUE TITLE
Dropdown supposition in IE 11.0 

### ISSUE THREAD

**Issue by marcustisater** [joeldbirch/superfish#149]
Howdy,

It seems to be a problem in IE 11.0 were the Superfish dropdown sub-menu acts differently and gets out of window when there are too many menu-items to display. I guess this has to do with Supposition or the HoverIntent.

Are there any updates for supposition or is it built-in with Superfish? 

Thank you.

**Comment by joeldbirch** [comment]
Supposition is not officially supported, although I'd love for someone to adopt it and make it their own repo.
