### ISSUE TITLE
Split CSS

### ISSUE THREAD

**Issue by marcohanke** [joeldbirch/superfish#150]
Hey there,
is it possibel to split the css into an superfish.css and theme.css
So the customer can update superfish easyly without overwriting theme.css

**Comment by joeldbirch** [comment]
I'm reluctant to do this because it would encourage people to add them to their website as separate files, reducing performance. Maybe I'll do it once http/2 is ubiquitous.

Also, the CSS only very rarely changes. Usually only during major releases.
