### ISSUE TITLE
Superfish with single page website

### ISSUE THREAD

**Issue by Foundas** [joeldbirch/superfish#152]
Hi team,

i am using superfish for a single page website and on mobile, the problem is that the window stays open even if you select one of the menu links.
I played around and added the following code.

$(document).ready(function() {
	window.addEventListener("hashchange", function(){
		$('.rd-mobilemenu_ul').hide();
		$('.rd-mobilemenu').toggleClass("active");
		$('.rd-mobilepanel_toggle').toggleClass("active");
		$(".rd-mobilepanel_toggle").on("click", function () {
			$('.rd-mobilemenu_ul').show();
		});
	},  false);
});

Now, when you select one of the menu items, the mobile menu closes but user has to click twice on the screen in order to accept a command (either scroll the page or click a hyperlink)

Apparently, my code is not correct or im missing something like a focus on the page?

Can you please advice how i can make the superfish on mobile to close when an item is selected?

thanking you in advance

**Comment by joeldbirch** [comment]
Try calling the `hide` method inside a click handler on the menu item's parent `LI` element(s). Something like this:

```js
$('.sf-menu').on('click', 'a', function(){
    $(this).parents('li').superfish('hide');
});
```
