### ISSUE TITLE
Can i change hover delay that used by hoverIntent.js?

### ISSUE THREAD

**Issue by MoradHamdy** [joeldbirch/superfish#153]
Hi there,

I'm looking forward to be able to change the hover time delay that used through hoverIntent.js . I found this issue that almost talked about this here: https://github.com/joeldbirch/superfish/issues/120

but i failed. Is there any guide for that?

**Comment by joeldbirch** [comment]
Sorry, but Superfish only uses the default hoverIntent delay on mouseover, and uses its own for mouseout (as discussed at #120).
