### ISSUE TITLE
Use of toggleClass

### ISSUE THREAD

**Issue by daviddeutsch** [joeldbirch/superfish#154]
This threw me off tremendously - If, for whatever reason, you have classes set in your markup, they will disappear due to the use of toggleClass. So if you have cssArrows:true, but sf-arrows as a class in your menu, it will then have no arrows.

I don't really see how toggleClass is of use on init() - perhaps I'm missing something, but just exchanging that for addClass (at least during init) should be a no-brainer, I think.

**Comment by joeldbirch** [comment]
Hmm, thanks again, I'll check it out.

**Comment by daviddeutsch** [comment]
Thanks for the update, @joeldbirch!
