### ISSUE TITLE
how to exclude one menu item of using superfish

### ISSUE THREAD

**Issue by konfuzius** [joeldbirch/superfish#156]
I have a menu with n submenus and one search sub menu (S_A_F_S_G_H_Search).
I can't and won't separate those "two" things - take search menu item out of main navigation.

I only want **disable suprefish** (sfHover inject) **on** that **one menu item**, to get hoverable sub menus and one onclick opening sub menu.

I found a bad solution - _onInit_ find a selected group and stay focused till submit button was triggered and _onHide_ close search sub menu.

Your solutions?

**Comment by joeldbirch** [comment]
Sorry, this not the correct place for individualised implementation support.
