### ISSUE TITLE
Release 1.4.x

### ISSUE THREAD

**Issue by lpalgarvio** [joeldbirch/superfish#157]
Hello

Where are the releases 1.4.x?

**Comment by jhabdas** [comment]
@lpalgarvio Can this be closed? /cc @joeldbirch

**Comment by lpalgarvio** [comment]
Well, we were looking into these releases for projects that are using Drupal 7's Superfish contrib module.
https://www.drupal.org/project/superfish

**Comment by jhabdas** [comment]
Sounds like a Drupal concern to me.

**Comment by lpalgarvio** [comment]
We're asking for a git tag / github release pointing to the latest stable version of superfish 1.4.x.
That's all, that is superfish concern, not drupal. Drupal is just a consumer.
Many minor versions of superfish are published, but not this one, which was very popular.

**Comment by jhabdas** [comment]
Superfish is on 1.7.9. There were no git tags used on this repo back in '13. I don't think most people even knew how to use GH 4 years ago. If you can't point at a specific commit SHA I'd say that's a Drupal problem. If I'm misunderstanding something, I apologize. But all the code you should need is right here.

**Comment by lpalgarvio** [comment]
That's what I found out before, no tags. The point is not whether I can or not point to specific commits, which I can and have done before. The point is for users at large and more specifically, usage in tools such as Composer, which is not pleasant when releases don't exist and you need to create a custom fake repository in your configuration to select a specific commit. But all this can be easily fixed with a git tag & git push --tags, as long as you know the commit.

**Comment by jhabdas** [comment]
https://github.com/mehrpadin/Superfish-for-Drupal

**Comment by jhabdas** [comment]
That repo says 1.4.8. Is that what you're actually looking for?

**Comment by lpalgarvio** [comment]
thanks
