### ISSUE TITLE
On mobile submenus not showing

### ISSUE THREAD

**Issue by manolo143** [joeldbirch/superfish#179]
Hello. I'm having an issue where on desktop my submenu is displayed but on mobile it does not. and it doesn't show the submenu indicator.
When I rotate my phone horizontally I get the full menu and am able to see the submenu. but not vertically.
Please help.
website is www.1wayav.com

**Comment by joeldbirch** [comment]
Please follow the recommended support options here https://superfish.joelbirch.design/download/#support
