### ISSUE TITLE
Busted link in the README

### ISSUE THREAD

**Issue by joelhsmith** [joeldbirch/superfish#183]
Location of problem: README.md  

Expected behavior: The link to "`[existing Superfish documentation](uperfish.joelbirch.co/)`" has a link to the page superfish.joelbirch.co.

Actual behavior: It goes to a busted link.

```
This site can’t be reachedsuperfish.joelbirch.co’s server 
IP address could not be found.
```

Solution: Add https:// to the beginning of the link.

**Comment by joeldbirch** [comment]
Thanks! The correct URL ends in `.design` and I have just updated both URLs in the readme to reflect this.
