### ISSUE TITLE
Remove useClick feature?

### ISSUE THREAD

**Issue by joeldbirch** [joeldbirch/superfish#47]
I'm regretting adding the `useClick` feature as it increases the complexity of the code and eats up development time that I'd prefer to spend focussing on hover events (plus touch and keyboard support, of course), which is truer to the mission of Superfish.

I think it would be a better idea to have a separate click menu plugin, allowing me to remove some complexity and bloat from Superfish and making room for further enhancements. I'm not seeing much benefit of having both click and hover capability in the one plugin, and the amount of `if (o.useClick) {…` forks that keep needing to be added is telling.

I'd really appreciate hearing some opinions on this.

**Comment by dalin-** [comment]
One downside of hover is with a non-touch device that has a small viewport, it's tricky to navigate a mobile-optimized menu with hovers.  You have to be really precise with the pointer and things open/close like wild.

**Comment by chriskuku** [comment]
Hi,
I have a problem with a mobile-menu which might stem from code developed and discussed here.
Have a look at http://krischu.bplaced.net/test.html

When the mobile-menu appears I would like to be able to navigate to a node point. At the moment the menu is constructed in a way that clicking on the first level (node) only the submenu opens. 

Would it be possible to modify the code such that with a click on the left side the node's URL opens
(in the case of the example: /ueber-uns/test.html) , with a click on the arrow in the right, the submenu drops down and can be navigated to by clicking on the link there (/ueber-uns/history/test.html)?

Thanks for helping.

--
Christoph

**Comment by joeldbirch** [comment]
Hello,

Sorry, that site doesn't use Superfish.

**Comment by chriskuku** [comment]
Oh, sorry. Just thought because it was using class names like sf-sub-indocator and other class names starting with sf-.
