### ISSUE TITLE
Submenu close on item selection

### ISSUE THREAD

**Issue by FredFrin** [joeldbirch/superfish#69]
Hi,

Great plugin - although for me it's missing one small feature: an option to allow
closing of the drop-down submenu when a submenu item has been selected by 
clicking on it.

Is this something that could be added? 

cheers,
FF

**Comment by ronman** [comment]
I am doing something similar, but having the problem on iPad2/Safari that the submenus correctly close but leave the top level menu highlighted, and it stays highlighted even when selecting a different top level menu element.

This is in an app that does not reload the page, every menu selection causes an Ajax call, an increasingly common way of doing things.

I didn't have success with exactly the code above, here's my adaptation that works except for the persistent highlighting:

       // get all anchors in menu tree
      $('ul.sf-menu').find('a').on("click", function(event) {
        event.preventDefault();
        // back up to the li.sfHover element 
        $(this).parents('.sfHover').superfish('hide');
        // a little inefficient but simple
        $('ul.sf-menu').find('li.sfHover').removeClass('sfHover');
      });

How to recover the normal state for the top-level menu item after superfish('hide')?
