### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sfTimer' of undefined

### ISSUE THREAD

**Issue by wojtech** [joeldbirch/superfish#88]
Hi,

I'm getting the following console error (despite the menu working fine)
Uncaught TypeError: Cannot read property 'sfTimer' of undefined
when moving mouse above dropdown part of the menu.

Best,
Wojciech

**Comment by alel890** [comment]
Hi, i have the same issue. 
The error in console: Uncaught TypeError: Cannot read property 'sfTimer' of null
The lines of the plugin that send the error: 

clearTimeout(o.sfTimer), s.siblings().superfish("hide").end().superfish("show")
 o ? e.proxy(f, s, n)() : (clearTimeout(n.sfTimer), n.sfTimer = setTimeout(e.proxy(f, s, n), n.delay))

My code: 
I'm getting this menu from a file named 'menu.html' with ajax/jquery
## menu.html:

`<div class="nicdark_section nicdark_navigation fade-down">
    
    <div class="nicdark_menu_boxed">

        <div class="nicdark_section nicdark_bg_greydark nicdark_displaynone_responsive">
            <div class="nicdark_container nicdark_clearfix">
                <div class="grid grid_6">
                    <div class="nicdark_focus">
                        <h6 class="white">
                            <i class="icon-calendar-outlilne"></i>&nbsp;&nbsp;<a class="white" href="">EVENTOS</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<span class="grey">·</span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="icon-pencil-1"></i>&nbsp;&nbsp;<a class="white" href="">NOVEDADES</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<span class="grey">·</span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="icon-phone-outline"></i>&nbsp;&nbsp;(+54) 02214251307
                        </h6>
                    </div>
                </div>
                <div class="grid grid_6 right">
                    <div class="nicdark_focus right">
                        <h6 class="white">
                            <i class="icon-globe-alt-outline"></i>&nbsp;&nbsp;<a class="white nicdark_mpopup_window" href="#nicdark_window">IDIOMAS</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<span class="grey">·</span>&nbsp;&nbsp;&nbsp;&nbsp;
                           
                    </div>
                </div>

                
                <div id="nicdark_window" class="nicdark_bg_white nicdark_radius zoom-anim-dialog mfp-hide">
                    
                    <div class="nicdark_textevidence nicdark_bg_red nicdark_radius_top">
                        <div class="nicdark_margin20">
                            <h4 class="white">IDIOMAS</h4>
                        </div>
                    </div>

                    <div class="nicdark_margin20">
                        
                        <ul class="nicdark_list border">
                        
                            <li class="nicdark_border_grey">
                                <p><a class="grey" href="">ESPAÑOL</a><a href="" class="nicdark_btn right nicdark_opacity"><img alt="" width="30" src="img/flag/img1.png"></a></p>
                                <div class="nicdark_space15"></div>
                            </li>

                           

                            <li class="nicdark_border_grey">
                                <div class="nicdark_space15"></div>
                                <p><a class="grey" href="">ITALIANO</a><a href="" class="nicdark_btn right nicdark_opacity"><img alt="" width="30" src="img/flag/img4.png"></a></p>    
                            </li>
                                
                        </ul>

                    </div>
                </div>
                

            </div>
        </div>

        <div class="nicdark_space3 nicdark_bg_gradient"></div>
                    
        <div class="nicdark_section nicdark_bg_grey nicdark_bg_greyheight  nicdark_shadow nicdark_radius_bottom">
            <div id="containNavResponsive" class="nicdark_container nicdark_clearfix">

                <div class="grid grid_12 percentage">
                        
                        <div class="nicdark_logo">
                            <a href="index.php">
                                <img alt="isotipo" src="img/marca.png">
                            </a>
                        </div>
                        <div class="nicdark_logo2 nicdark_marginleft10">
                            <img alt="logotipo" src="img/logo.png">
                        </div>

                        
                        
                        <nav>
                            <ul class="nicdark_menu nicdark_margin010 nicdark_padding50">

                               
                                <li class="red">
                                    <a href="#">INSTITUCIONAL</a>
                                    <ul class="sub-menu">
                                        <li><a href="">Historia</a></li>
                                        <li>
                                            <a href="">Comisión Directiva</a>
                                        </li>
                                         <li>
                                            <a href="">Equipo de trabajo</a>
                                        </li>
                                        
                             
                                    </ul>
                                </li>
                                
                                <li class="green nicdark_megamenu">
                                    <a href="#">PROPUESTA EDUCATIVA</a>
                                    <ul class="sub-menu">
                                        <li class="mm_grid mm_grid_3">
                                            <a href="#">Nivel Inicial</a>
                                            <ul class="sub-menu">
                                                <li><a href="#">Propuesta Educactiva</a></li>
                                                <li><a href="#">Objetivos</a></li>
                                                <li><a href="#">Diseño curricular</a></li>
                                            </ul>
                                        </li>
                                        <li class="mm_grid mm_grid_3">
                                            <a href="#">Nivel Primario</a>
                                            <ul class="sub-menu">
                                                <li><a href="#">Propuesta Educactiva</a></li>
                                                <li><a href="#">Objetivos</a></li>
                                                <li><a href="#">Diseño curricular</a></li>
                                            </ul>
                                        </li>
                                        <li class="mm_grid mm_grid_3">
                                            <a href="#">Nivel Secundario</a>
                                            <ul class="sub-menu">
                                               <li><a href="#">Propuesta Educactiva</a></li>
                                                <li><a href="#">Objetivos</a></li>
                                                <li><a href="#">Diseño curricular</a></li>
                                            </ul>
                                        </li>
                                        <li class="mm_grid mm_grid_3">
                                            <a href="#">Educación Terciaria</a>
                                            <ul class="sub-menu">
                                              <li><a href="#">Objetivos</a></li>
                                                <li><a href="#">Profesorado de Educación Física</a></li>
                                                <li><a href="#">Profesorado de Italiano</a></li>
                                               
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                               
                                <li class="red">
                                    <a href="">ACTIVIDADES</a>
                                    <ul class="sub-menu">
                                        <li><a href="">Proyectos</a></li>
                                        <li><a href="">Salidas Educativas</a></li>
                                         <li><a href="">Trabajos de Alumnos</a></li>
                                          <li><a href="">Torneos</a></li>
                                           <li><a href="">Olimpíadas</a></li>
                                            <li><a href="">Conferencias</a></li>
                                    </ul>
                                </li>
                                <li class="green">
                                    <a href="">CONTACTO</a>
                                </li>
                            </ul>
                        </nav>
    
                        <div class="nicdark_space20"></div>

                </div>

            </div>
            

        </div>
        

    </div>

</div>`

In the main html my code:
## **Code JS:**
`jQuery(document).ready(function() {
            // Get menu y footer a traves de ajax
            // ---------------------------------------------
            var divmenu = $("#div-menu");
            $.getScript("js/settings.js",function(){
                $.get("menu.html",function(infoMenu){
                divmenu.html(infoMenu);
                });
            });
});`

The file settings.js have:

**## Code JS**
`(function($) {
	"use strict";
	$('.nicdark_menu').superfish({
		delay: 1200
	});	
	//megamenu
	$('.nicdark_megamenu ul a').removeClass('sf-with-ul');
	$($('.nicdark_megamenu ul li').find('ul').get().reverse()).each(function(){
	  $(this).replaceWith($('<ol>'+$(this).html()+'</ol>'))
	});
}`

I can't find the solution and i've been trying for a long time.

Help mee!

Thanks a **lot!**

**Comment by joeldbirch** [comment]
Please see this page for your support options. You will also need to provide a live example of your problem page so someone can help you debug it.

**Comment by alel890** [comment]
I fix it! It was an error in html! Thanks

**Comment by DarkteK** [comment]
Answer from **joeldbirch** worked like a charm, thx!
